name: codeword
description: A game based off the Codenames game
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0-262.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  network_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/black.png
    - assets/blue.png
    - assets/red.png
    - assets/tan.png
